### ISSUE TITLE
Historical usage & sensors data?

### ISSUE THREAD

**Issue by begna112** [MizterB/homeassistant-infinitude#30]
I'm not familiar with either Home Assistant or Infinitude, so apologies if this should be obvious. 

I just bought a house with an Infinity system and one of the major benefits I was hoping to gain with a smart thermostat was historical usage data. Now that my ecobee dreams have been crushed, I'm hoping Infinitude can provide this data. 

I wasn't able to see anything in the readme that indicates that it stores usage or sensor data anywhere. However, looks like it displays the current temperature/humidity/airflow and your settings. 

So does this component and HA store the data anywhere? Or could it be configured to?

**Comment by MizterB** [comment]
The short answer is yes - the historical state of the Infinitude 'climate' entity is stored in Home Assistant by default (see HA's 'recorder' component for more info).  More detailed information from Infinitude is stored as attributes of the thermostat's 'climate' entity in HA (such as target/actual temps, HVAC state, etc.)  You can see these in the Developer Tools > States.  If you want to easily retrieve or graph historical data for these attributes, the best thing to do is a 'template sensor' for each attribute you want to track, and any changes to those attributes will also be saved.

That data is available - you just need to configure HA to manage it the way that you'd like.  Just keep reading the HA documentation ;)

**Comment by begna112** [comment]
Great! Thanks for confirming so I know I'm making the right choice going down the rabbit hole.

**Comment by scyto** [comment]
@MizterB  i had been playing with this and struggling to get HA to see the value as a temperature (i.e. automatically append F to it); i think the integration declares the state with out declaring the unit of measurement? (i have been (mis)reading the developer docs and thus have no actual clue what I am talking about.

So this
```
sensor:
  - platform: template
    sensors:
      basement_zone_temperature:
        friendly_name: "Basement Floor Temperature"
        device_class: temperature
        unit_of_measurement: temperature
        value_template: "{{ state_attr('climate.basement', 'current_temperature') }}"
```
results in this....
![image](https://user-images.githubusercontent.com/11369180/116162215-2deba080-a6aa-11eb-8cff-e42ea4656152.png)

**Comment by scyto** [comment]
doh, i am stupid for thinking it was programmatic - it is just a text label, so this works.
```
sensor:
  - platform: template
    sensors:
      upstairs_zone_temperature:
        friendly_name: "Upstairs Temperature"
        device_class: temperature
        unit_of_measurement: °F
        value_template: "{{ state_attr('climate.upstairs', 'current_temperature') }}"
      ground_floor_zone_temperature:
        friendly_name: "Ground Floor Temperature"
        device_class: temperature
        unit_of_measurement: °F
        value_template: "{{ state_attr('climate.ground_floor', 'current_temperature') }}"
      basement_zone_temperature:
        friendly_name: "Basement Floor Temperature"
        device_class: temperature
        unit_of_measurement: °F
        value_template: "{{ state_attr('climate.basement', 'current_temperature') }}"
```
