### ISSUE TITLE
Exposing oat as a sensor in Home Assistant

### ISSUE THREAD

**Issue by secabeen** [MizterB/homeassistant-infinitude#33]
Can we add a sensor entity that exposes the oat (Outdoor Air Temperature)?  That's useful data, especially for graphing against the other climate data we get.  Other sensors like rh (Relative Humidity) would be useful too,

**Comment by marcteale** [comment]
This is already accessible.  This is my configuration:

```yaml
  - platform: template
    sensors:
      thermostat_outside:
        friendly_name: "Thermostat Temperature - Outside"
        unit_of_measurement: '°F'
        value_template: "{{ state_attr('climate.zone_1', 'outdoor_temperature') }}"
        device_class: temperature

**Comment by secabeen** [comment]
Oh cool.  That would go in configuration.yaml?

Do we want to put that in the documentation in the README.md?

**Comment by secabeen** [comment]
For people seeing this later, here's the new style config:
```
template:
  sensor:
    - name: "Outside Temperature"
      unique_id: "outside_compressor_temp"
      unit_of_measurement: '°F'
      state: "{{ state_attr('climate.central_hvac', 'outdoor_temperature') }}"
```
