### ISSUE TITLE
Fan Status and Humidifier Status no longer work since 2023.5.1

### ISSUE THREAD

**Issue by greggitter** [MizterB/homeassistant-infinitude#56]
Looking for some help on config for **fan mode** and **humidifier status**.  Since updating to 2023.5.1 these two sensors are creating error messages and showing as "Unknown" (there were only warnings prior).  The log message is one I've searched for without ever finding an answer (hours).  Here's a snippet of my config containing the two invalid entries related to infinitude:

```
template:
  - sensor:
      - name: "HVAC Fan Mode"
        unique_id: fan_mode
        icon: mdi:fan
        unit_of_measurement: ""
        state: >
          {{(state_attr('climate.infinity', 'fan_mode') )}}

      - name: "HVAC Current Activity"
        unique_id: current_activity
        icon: mdi:thermometer
        unit_of_measurement: ""
        state: >
          {{(state_attr('climate.infinity', 'current_activity') )}}

      - name: "HVAC IDU Modulation"
        unique_id: idu_modulation
        icon: mdi:thermometer
        unit_of_measurement: "%"
        state: >
          {{(state_attr('climate.infinity', 'idu_modulation') )}}

      - name: "HVAC Humidifier Status"
        unique_id: humid
        icon: mdi:thermometer
        unit_of_measurement: ""
        state: >
          {{(state_attr('climate.infinity', 'humid') )}}
```

The error messages are:

```
ValueError: Sensor sensor.hvac_fan_mode has device class None, state class None unit  and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: low (<class 'str'>)
2023-05-05 13:41:25.706 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
```
I'm not sure how to define this item as string, if it's needed in the config or in the infinitude program.  Any help is greatly appreciated.

Thanks.
